resources:
- name: discord-bot
  type: git
  source:
    uri: https://((github_apikey))@github.com/cluedtke/discord-bot-drink-water.git
    branch: main

jobs:
- name: deploy-bot
  plan:
  - get: discord-bot
    trigger: true
  - task: build
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: node, tag: '18' }
      params:
        DISCORD_BOT_TOKEN: ((discord_bot_token))
      inputs:
      - name: discord-bot
      outputs:
      - name: discord-bot
      run:
        path: /bin/sh
        args:
        - -exc
        - |
          cd discord-bot
          npm cache clean --force
          npm install
  - task: terraform
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: hashicorp/terraform, tag: 'latest' }
      params:
        AWS_ACCESS_KEY_ID: ((aws_access_key_id))
        AWS_SECRET_ACCESS_KEY: ((aws_secret_access_key))
        TF_VAR_discord_bot_token: ((discord_bot_token))
      inputs:
      - name: discord-bot
      run:
        path: /bin/sh
        args:
        - -exc
        - |
          cd discord-bot/terraform
          terraform init
          terraform apply -auto-approve
